//
// Created by KirilliriK on 22.03.2021.
//

#ifndef ANOTHERWORD_COLOR_H
#define ANOTHERWORD_COLOR_H

#include <windows.h>


enum class Color {
    Black       = 0,
    Grey        = FOREGROUND_INTENSITY,
    LightGrey   = FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE,
    White       = FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    Blue        = FOREGROUND_BLUE,
    Green       = FOREGROUND_GREEN,
    Cyan        = FOREGROUND_GREEN | FOREGROUND_BLUE,
    Red         = FOREGROUND_RED,
    Purple      = FOREGROUND_RED   | FOREGROUND_BLUE,
    LightBlue   = FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
    LightGreen  = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    LightCyan   = FOREGROUND_GREEN | FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
    LightRed    = FOREGROUND_RED   | FOREGROUND_INTENSITY,
    LightPurple = FOREGROUND_RED   | FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
    Orange      = FOREGROUND_RED   | FOREGROUND_GREEN,
    Yellow      = FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
};

enum class BackgroundColor {
    Black       = 0,
    Grey        = BACKGROUND_INTENSITY,
    LightGrey   = BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_BLUE,
    White       = BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    Blue        = BACKGROUND_BLUE,
    Green       = BACKGROUND_GREEN,
    Cyan        = BACKGROUND_GREEN | BACKGROUND_BLUE,
    Red         = BACKGROUND_RED,
    Purple      = BACKGROUND_RED   | BACKGROUND_BLUE,
    LightBlue   = BACKGROUND_BLUE  | BACKGROUND_INTENSITY,
    LightGreen  = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
    LightCyan   = BACKGROUND_GREEN | BACKGROUND_BLUE  | BACKGROUND_INTENSITY,
    LightRed    = BACKGROUND_RED   | BACKGROUND_INTENSITY,
    LightPurple = BACKGROUND_RED   | BACKGROUND_BLUE  | BACKGROUND_INTENSITY,
    Orange      = BACKGROUND_RED   | BACKGROUND_GREEN,
    Yellow      = BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
};


#endif //ANOTHERWORD_COLOR_H
